depot123/config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
devise_for :users
get 'admin' => 'admin#index'
controller :sessions do
get 'login' => :new
post 'login' => :create
delete 'logout' => :destroy
end
  get 'sessions/create'

  get 'sessions/destroy'

resources :users
  
resources :products 
resources :histories
resources :profile

scope '(:locale)' do
resources :orders
resources :line_items
resources :carts
root 'store#index', as: 'store', via: :all
end

end

depot123/app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

depot123/app/models/history.rb
class History < ActiveRecord::Base
has_many :line_items
belongs_to :user
end

depot123/app/models/line_item.rb
class LineItem < ActiveRecord::Base
belongs_to :product
belongs_to :order
belongs_to :user
belongs_to :history
belongs_to :profile

def total_price
  product.price*quantity 
end


end

depot123/app/models/order.rb
class Order < ActiveRecord::Base
has_many :line_items, dependent: :destroy
belongs_to :user
after_create :add_status
PAYMENT_TYPES = [ "Check", "Credit card", "Purchase order" ]
validates :name,  presence: true
validates :pay_type, inclusion: PAYMENT_TYPES

def add_status
  self.update_attributes(status: "pending")
end

end

depot123/app/models/product.rb
class Product < ActiveRecord::Base
has_many :line_items
has_many :orders, through: :line_items
has_attached_file :image
before_destroy :ensure_not_referenced_by_any_line_item

validates :title, :description, presence: true
validates :price, numericality: {greater_than_or_equal_to: 0.01}
validates :title, uniqueness: true


validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

def self.latest
  Product.order(:updated_at).last
end
 def add_product(product_id, current_user)
        current_item = current_user.line_items.where(:order_id => nil).find_by(product_id: product_id)
         if current_item
          current_item.quantity += 1
         else
          current_item = current_user.line_items.build(product_id: product_id)
      end
        
      current_item
   end
def delete_product(product_id, current_user)
        current_item = current_user.line_items.where(:order_id => nil).find_by(product_id: product_id)
         if current_item
          current_item.quantity -= 1
         else
          current_item = current_user.line_items.destroy(product_id: product_id)
      end
        
      current_item
   end

private

# ensure that there are no line items referencing this product
 def ensure_not_referenced_by_any_line_item
  if line_items.empty?
    return true
  else
    errors.add(:base, 'Line Items present')
    return false
  end
 end
end

depot123/app/models/user.rb
class User < ActiveRecord::Base
after_create :add_user_role
after_destroy :ensure_an_admin_remains
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  #validates :name, presence: true, uniqueness: true
  #has_secure_password

has_many :line_items
has_many :orders
has_many :histories

def add_user_role
    self.update_attributes(role: "user")
end

 private
 def ensure_an_admin_remains
  if User.count.zero?
    raise "Can't delete last user"
  end
 end
end

  

depot123/app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  @total_orders = Order.count
  end
end

depot123/app/controllers/store_controller.rb
class StoreController < ApplicationController
  skip_before_action :authorize

  def index
    if params[:set_locale]
      redirect_to store_url(locale: params[:set_locale])
    else
       @products = Product.order(:title)
    end
  end
end

  

depot123/app/helpers/admin_helper.rb
module AdminHelper
end

depot123/app/helpers/application_helper.rb
module ApplicationHelper
  def hidden_div_if(condition, attributes = {}, &block)
    if condition
       attributes["style"] = "display: none"
    end
    content_tag("div", attributes, &block)
  end
end

depot123/app/helpers/carts_helper.rb
module CartsHelper
end

depot123/app/helpers/histories_helper.rb
module HistoriesHelper
end

depot123/app/helpers/line_items_helper.rb
module LineItemsHelper
end

depot123/app/helpers/orders_helper.rb
module OrdersHelper
end

depot123/app/helpers/products_helper.rb
module ProductsHelper
end

depot123/app/helpers/profile_helper.rb
module ProfileHelper
end

depot123/app/helpers/profiles_helper.rb
module ProfilesHelper
end

depot123/app/helpers/sessions_helper.rb
module SessionsHelper
end

depot123/app/helpers/store_helper.rb
module StoreHelper
end

depot123/app/helpers/users_helper.rb
module UsersHelper
end

depot123/app/views/admin/index.html.erb
<h1>Welcome</h1>
It's <%= Time.now %>
We have <%= pluralize(@total_orders, "order") %>.

depot123/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Online Store</title>
<%= stylesheet_link_tag "application", media: "all","data-turbolinks-track" => true %>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name %>">

<div id="banner">
<%= image_tag("online_shopping.jpeg") %>
<%= @page_title || t('.title') %>
<%= form_tag store_path, class: 'locale' do %>
<%= select_tag 'set_locale', options_for_select(LANGUAGES, I18n.locale.to_s), onchange: 'this.form.submit()' %>
<%= submit_tag 'submit' %>
<%= javascript_tag "$('.locale input').hide()" %>
<% end %>
</div>
<% if user_signed_in? %>
  
   You are currently signed in as <%= current_user.email %>,not you?
 
 
   <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
<% else %>
 
   <%= link_to "Sign up!", new_user_registration_path %> or <%= link_to "Sign in", new_user_session_path %>
  
<% end %>
<div id="columns">

<div id="side"style="background-color:#E9967A; height:1200px;width:170px;float:left;">

<ul>
<li><a href="http://localhost:3000/en"><%= t('.home') %></a></li>
</ul>
<% if session[:user_id] %>
<ul>
<li><%= link_to t('.orders'), orders_path%></li>
<li><%= link_to t('.products'), products_path %></li>
<li><%= link_to t('.users'), users_path%></li>
</ul>
<%= button_to 'Logout', logout_path, method: :delete %>
<% end %>
<% if (user_signed_in? && current_user.role == 'admin') %>


              <li><%=link_to t('.home'), admin_path %></li>
              <li><%= link_to t('.orders'), orders_path%></li>
              <li><%= link_to t('.products'), products_path %></li>
              <li><%= link_to t('.users'), users_path %></li>
              </ul>
              <%else%>
              <li><%= link_to t('.history'), histories_path %></li>
              <li><%= link_to t('.profile'), current_user %></li>
              </ul>

<% end %>
</div>


<div id="main">
<%= yield %>
</div>
</div>
</body>
</html>

depot123/app/views/order_notifier/received.html.erb
Dear <%= @order.name %>
<h3>Pragmatic Order received</h3>
<p>
This is just to let you know that u've received your recent order:
</p>
<table>
<tr><th colspan="2">Qty</th><th>Description</th></tr>
<%= render @order.line_items -%>
</table>

depot123/app/views/order_notifier/received.text.erb
Dear <%= @order.name %>
Thank you for your recent order from The Pragmatic Store.
You ordered the following items:
<%= render @order.line_items -%>
We'll send you a separate e-mail when your order ships.

depot123/app/views/order_notifier/shipped.html.erb
<h3>Order Shipped</h3>
<p>
This is just to let you know that we've shipped your recent order:
</p>
<table>
<tr><th colspan="2">Qty</th><th>Description</th></tr>
<%= render @order.line_items -%>
</table>

depot123/app/views/order_notifier/shipped.text.erb
OrderNotifier#shipped

<%= @greeting %>, find me in app/views/order_notifier/shipped.text.erb