depot123/config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
devise_for :users
get 'admin' => 'admin#index'
controller :sessions do
get 'login' => :new
post 'login' => :create
delete 'logout' => :destroy
end
  get 'sessions/create'

  get 'sessions/destroy'

resources :users
  
resources :products 
resources :histories
resources :profile

scope '(:locale)' do
resources :orders
resources :line_items
resources :carts
root 'store#index', as: 'store', via: :all
end

end

depot123/app/models/line_item.rb
class LineItem < ActiveRecord::Base
belongs_to :product
belongs_to :order
belongs_to :user
belongs_to :history
belongs_to :profile

def total_price
  product.price*quantity 
end


end

depot123/app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController

  before_action :set_line_item, only: [:show, :edit, :update, :destroy]



  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
   @product = Product.find(params[:product_id])
   @line_item = @product.add_product(@product.id, current_user)

   respond_to do |format|
      if @line_item.save
      
        format.html { redirect_to line_items_url }

        format.js { @current_item = @line_item }


        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
      @line_item = LineItem.find(params[:id])
        if @line_item.quantity > 1
         @quantity = @line_item.quantity - 1
         puts @quantity
         puts "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
           @line_item.update_attribute("quantity","#{@quantity}")
            #@order.update_attribute("totalprice", "#{@totalpri}")
           respond_to do |format|
         format.html { redirect_to line_items_path,notice: 'item removed' }
         format.json { head :no_content }
  end
       else
      @line_item.destroy
      respond_to do |format|
     format.html { redirect_to mycart_list_path,notice: 'item removed' }
    format.json { head :no_content }
     end
      end
   end

 


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
     params.require(:line_item).permit(:product_id)
   end

end

depot123/app/helpers/line_items_helper.rb
module LineItemsHelper
end

depot123/app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br>
    <%= f.text_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

depot123/app/views/line_items/_line_item.html.erb
<% if line_item == @current_item %>
<tr id="current_item">
<% else %>
<tr>
<% end %>
<td><%= line_item.quantity %>&times;</td>
<td><%= line_item.product.title %></td>
<td class="item_price"><%= number_to_currency(line_item.total_price) %></td>
</tr>

depot123/app/views/line_items/_line_item.text.erb
<%= sprintf("%2d x %s",
line_item.quantity,
truncate(line_item.product.title, length: 50)) %>

depot123/app/views/line_items/create.js.erb
 $('#notice').hide();


if ($('#cart tr').length == 1) { $('#cart').show('blind', 1000); }

$('#cart').html("<%= escape_javascript render(@cart) %>");

$('#current_item').css({'background-color':'#88ff88'}).
animate({'background-color': '#B0C4DE'}, 1000);

depot123/app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

depot123/app/views/line_items/index.html.erb
<h1>Listing line_items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Quantity</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
     <% @arr = Array.new %>
   <% current_user.line_items.all.where("status = ?", 0).each do |item| %>

      <tr>
        <td><%=item.product.title %></td>
        <td><%=item.quantity %></td>
        <td><%=number_to_currency(item.total_price) %></td>
        <td class="list_actions">
          <%= link_to 'Show', item %><br/>
          <%= link_to 'Remove', item, method: :delete, data: { confirm: 'Are you sure?' } %>
       </td>
        <% @arr << item.total_price %>
      </tr>
    <% end %>
 
         <%$sum = @arr.sum %>
         <td><h6>Total Price</h6></td>
         <td>     </td>
         <td><h6><%= number_to_currency($sum) %></h6></td>
  </tbody>
</table>

    
<%= button_to t('.purchase'), new_order_path, method: :get %>
<%= link_to t('.Continue Shopping'), store_path %>

depot123/app/views/line_items/new.html.erb
<h1>New line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

depot123/app/views/line_items/show.html.erb
<p>
  <strong>Product:</strong>
  <%= @line_item.product.title %>
</p>



<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>